# Generated by Django 5.1.2 on 2024-12-10 01:51

import AdminApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=AdminApp.models.upload_to_overwrite)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kadai',
            fields=[
                ('category', models.CharField(choices=[('basic', '基本'), ('advance', '応用')], default='basic', max_length=10, verbose_name='問題区分')),
                ('number', models.CharField(default='a1', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='問題番号')),
                ('name', models.CharField(default='問題名', max_length=100)),
                ('q_text', models.TextField(default='問題文', verbose_name='問題文')),
            ],
            options={
                'db_table': 'kadai_table',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=40, unique=True)),
                ('html_file_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'materials_table',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_text', models.TextField(verbose_name='解答内容')),
                ('kadai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='AdminApp.kadai', verbose_name='問題')),
            ],
            options={
                'db_table': 'answer_table',
            },
        ),
    ]
