# Generated by Django 5.1.3 on 2024-11-30 11:46

import AdminApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=AdminApp.models.upload_to_overwrite)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
