# Generated by Django 5.1.2 on 2024-12-16 07:07

import AdminApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_id',
            field=models.CharField(default=AdminApp.models.Material.generate_uuid, editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='kadai',
            name='category',
            field=models.CharField(choices=[('基本区分', '基本'), ('応用区分', '応用'), ('チュートリアル', 'チュートリアル')], default='基本区分', max_length=10, verbose_name='問題区分'),
        ),
        migrations.AlterField(
            model_name='kadai',
            name='number',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='問題番号'),
        ),
        migrations.CreateModel(
            name='KadaiProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('未着手', 0), ('実行中', 1), ('完了', 2)], default='未着手', max_length=10, verbose_name='進捗状況')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('kadai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.kadai', verbose_name='課題')),
                ('user', models.ForeignKey(limit_choices_to={'groups_name': 'user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '課題進捗',
                'verbose_name_plural': '課題進捗',
                'db_table': 'progress_table',
                'unique_together': {('user', 'kadai')},
            },
        ),
    ]
