# Generated by Django 5.1.2 on 2024-12-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadai',
            name='number',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='問題番号'),
        ),
    ]
