# Generated by Django 5.1.3 on 2024-12-12 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_kadai_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KadaiProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('未着手', 0), ('実行中', 1), ('完了', 2)], default='未着手', max_length=10, verbose_name='進捗状況')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('kadai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.kadai', verbose_name='課題')),
                ('user', models.ForeignKey(limit_choices_to={'groups_name': 'user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '課題進捗',
                'verbose_name_plural': '課題進捗',
                'db_table': 'kadai_proguress_table',
                'unique_together': {('user', 'kadai')},
            },
        ),
    ]
