# Generated by Django 5.1.2 on 2024-12-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='AdminApp.kadai', verbose_name='問題')),
            ],
        ),
    ]
